{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbucket.creativeadvtech",
    "module": "tools",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.7.aar",
          "url": "tools-1.7.aar",
          "size": 325986,
          "sha512": "927d23c1548511a3014362372bb6a4a48deae1a2fbfbeb915aa78c83ebc92fd190b7b16409fd57c7e8c6e846e30f7692937d6cb2055a1c931f2df7020a7d5e37",
          "sha256": "be2d2e4f1f7c4541eb223b013c20729619f0fee028946fba9e06cdb72e79ae5a",
          "sha1": "55a8044a1dbf3779a81c5f23e18ae3b73edd0430",
          "md5": "278b3bfe46ad7d36dfa1492f85a5c589"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.12"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.synaptic-tools",
          "module": "traceroute",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.github.stealthcopter",
          "module": "AndroidNetworkTools",
          "version": {
            "requires": "0.4.5.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.7.aar",
          "url": "tools-1.7.aar",
          "size": 325986,
          "sha512": "927d23c1548511a3014362372bb6a4a48deae1a2fbfbeb915aa78c83ebc92fd190b7b16409fd57c7e8c6e846e30f7692937d6cb2055a1c931f2df7020a7d5e37",
          "sha256": "be2d2e4f1f7c4541eb223b013c20729619f0fee028946fba9e06cdb72e79ae5a",
          "sha1": "55a8044a1dbf3779a81c5f23e18ae3b73edd0430",
          "md5": "278b3bfe46ad7d36dfa1492f85a5c589"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.7-sources.jar",
          "url": "tools-1.7-sources.jar",
          "size": 77110,
          "sha512": "6b847aca0b721e0efea3b55e26f12bb96de6082849b6fa139ffb0a5d3232ee55110a419fbab8e601a5d28384962f2764596885e1cf6e20dc3f552c752c2d3118",
          "sha256": "eeab0c788d5d8172c70790e7c2105715f43fd49e627c9e724f27ae63a6339d88",
          "sha1": "6af747e07c2d97fbd6b01c4fb55c5b57a9908458",
          "md5": "a651a56c80c23806139abb25df49290c"
        }
      ]
    }
  ]
}
