// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.creativeadvtech.scanmynet_sdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * iOS `ScanMyNetConfiguration.Environment`. Android has no environment enum —
 * it takes an explicit [ScanConfig.baseUrl] string instead.
 * TODO(confirm): how iOS `environment` maps to an Android baseUrl, and whether
 * the host passes baseUrl OR environment. Native code maps explicitly; do NOT
 * rely on index parity.
 */
enum class ScanEnvironment(val raw: Int) {
  STAGING(0),
  PRODUCTION(1),
  TESTING(2);

  companion object {
    fun ofRaw(raw: Int): ScanEnvironment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Android `NetworkScanStep` — 13 values in source declaration order.
 * iOS has no equivalent enum (it emits a free-text stage label string), so on
 * iOS [ScanProgress.currentStep]/[nextStep] are null and [label] is set.
 */
enum class ScanStep(val raw: Int) {
  SETUP(0),
  ROUTER_UPNP(1),
  CONNECTIVITY_TEST(2),
  SPEED_TEST(3),
  PUBLIC_IP_FETCH(4),
  GPS_LOCATION_FETCH(5),
  TRACEROUTE(6),
  WIFI_CONGESTION_TEST(7),
  WIFI_DISCOVERY(8),
  CONNECTION_QUALITY_TEST(9),
  LAN_DISCOVERY(10),
  ADDITIONAL_DATA(11),
  RESULT_SUBMISSION(12);

  companion object {
    fun ofRaw(raw: Int): ScanStep? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Android `NetworkScanResultStatus`. (Source declares
 * ERROR_SUBMISSION_FAILED, SUCCESS — we keep our own order and map explicitly
 * in native code, never by index.)
 */
enum class ScanResultStatus(val raw: Int) {
  SUCCESS(0),
  SUBMISSION_FAILED(1);

  companion object {
    fun ofRaw(raw: Int): ScanResultStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Normalized error category across both platforms. */
enum class ScanErrorKind(val raw: Int) {
  /**
   * Non-fatal, per-step failure. Android `NetworkScanError`;
   * iOS `scanServiceFailed(type:error:)`. The scan continues.
   */
  PER_STEP(0),
  /**
   * Terminal submission failure. Android `scan()` Single.onError;
   * iOS `scanFailed`.
   */
  SUBMISSION(1),
  /** iOS `scanCanceled()`. Android has no cancel in this fork. */
  CANCELED(2);

  companion object {
    fun ofRaw(raw: Int): ScanErrorKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Flat configuration collapsing the Android 6-step builder and the iOS
 * `ScanMyNetConfiguration` into one message. The Android `Context` is supplied
 * by the plugin (applicationContext), so it is NOT a field here.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScanConfig (
  /** MANDATORY on both. Android `ApiKey.apiKey`; iOS `configuration.apiKey`. */
  val apiKey: String,
  /**
   * Android `UserKey.userKey` (sent as ReportParamDto.key). iOS: not used.
   * TODO(confirm): is iOS `requestKey` the same concept as Android `userKey`?
   */
  val userKey: String? = null,
  /** Android `AppName.appName` (ReportParamDto.app). iOS: not used. */
  val appName: String? = null,
  /**
   * Android `BaseUrl.baseUrl` (Retrofit base). iOS selects backend via
   * [environment] instead.
   */
  val baseUrl: String? = null,
  /** iOS `ScanMyNetConfiguration.requestKey`. Android: not used. */
  val requestKey: String? = null,
  /**
   * iOS only. If null on iOS, native defaults to [ScanEnvironment.production].
   * TODO(confirm) default environment.
   */
  val environment: ScanEnvironment? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanConfig {
      val apiKey = pigeonVar_list[0] as String
      val userKey = pigeonVar_list[1] as String?
      val appName = pigeonVar_list[2] as String?
      val baseUrl = pigeonVar_list[3] as String?
      val requestKey = pigeonVar_list[4] as String?
      val environment = pigeonVar_list[5] as ScanEnvironment?
      return ScanConfig(apiKey, userKey, appName, baseUrl, requestKey, environment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      userKey,
      appName,
      baseUrl,
      requestKey,
      environment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanConfig
    return MessagesPigeonUtils.deepEquals(this.apiKey, other.apiKey) && MessagesPigeonUtils.deepEquals(this.userKey, other.userKey) && MessagesPigeonUtils.deepEquals(this.appName, other.appName) && MessagesPigeonUtils.deepEquals(this.baseUrl, other.baseUrl) && MessagesPigeonUtils.deepEquals(this.requestKey, other.requestKey) && MessagesPigeonUtils.deepEquals(this.environment, other.environment)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.baseUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.environment)
    return result
  }
}

/**
 * Progress payload — superset of both platforms.
 * Android fills step/nextStep/percent/durationMs; iOS fills percent + label.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScanProgress (
  /**
   * 0..100. Native normalizes to this range.
   * TODO(verify): Android `NetworkScanProgress.percent` is a Float documented
   * as "percent of tests completed" — confirm 0..1 vs 0..100 and normalize in
   * the Kotlin bridge to match iOS `scanProgress` (0..100).
   */
  val percent: Double,
  /** Android `NetworkScanProgress.currentStep`. Null on iOS. */
  val currentStep: ScanStep? = null,
  /** Android `NetworkScanProgress.nextStep`. Null on iOS. */
  val nextStep: ScanStep? = null,
  /**
   * iOS stage label (`nextScanStarted(value)` / `serviceTriggered(log)`).
   * Null on Android.
   */
  val label: String? = null,
  /** Android `NetworkScanProgress.duration` (ms). Null on iOS. */
  val durationMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanProgress {
      val percent = pigeonVar_list[0] as Double
      val currentStep = pigeonVar_list[1] as ScanStep?
      val nextStep = pigeonVar_list[2] as ScanStep?
      val label = pigeonVar_list[3] as String?
      val durationMs = pigeonVar_list[4] as Long?
      return ScanProgress(percent, currentStep, nextStep, label, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      percent,
      currentStep,
      nextStep,
      label,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanProgress
    return MessagesPigeonUtils.deepEquals(this.percent, other.percent) && MessagesPigeonUtils.deepEquals(this.currentStep, other.currentStep) && MessagesPigeonUtils.deepEquals(this.nextStep, other.nextStep) && MessagesPigeonUtils.deepEquals(this.label, other.label) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.percent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.currentStep)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nextStep)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.label)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    return result
  }
}

/**
 * Terminal success. Android `ReportResponseDto.data`; iOS
 * `scanFinished(reportUrl:)`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScanResult (
  /**
   * The online report URL (Android value may carry a `verification_token`
   * query param — leave parsing to Dart).
   */
  val reportUrl: String,
  /** Android `NetworkScanResult.status`. iOS only emits on success -> SUCCESS. */
  val status: ScanResultStatus? = null,
  /** Android `NetworkScanResult.duration` (total ms). Null on iOS. */
  val totalDurationMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanResult {
      val reportUrl = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as ScanResultStatus?
      val totalDurationMs = pigeonVar_list[2] as Long?
      return ScanResult(reportUrl, status, totalDurationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reportUrl,
      status,
      totalDurationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanResult
    return MessagesPigeonUtils.deepEquals(this.reportUrl, other.reportUrl) && MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.totalDurationMs, other.totalDurationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reportUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.totalDurationMs)
    return result
  }
}

/**
 * Error payload. `Throwable`/`Error`/`HTTPURLResponse` are not channel-
 * encodable, so everything is flattened to primitives here.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScanError (
  val kind: ScanErrorKind,
  /** `Throwable.message` / `Error.localizedDescription` / raw response body. */
  val message: String,
  /** Android `NetworkScanError.test` (per-step). Null on iOS. */
  val step: ScanStep? = null,
  /** iOS `scanServiceFailed` type (`ServiceType.rawValue`). Null on Android. */
  val serviceType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanError {
      val kind = pigeonVar_list[0] as ScanErrorKind
      val message = pigeonVar_list[1] as String
      val step = pigeonVar_list[2] as ScanStep?
      val serviceType = pigeonVar_list[3] as String?
      return ScanError(kind, message, step, serviceType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      message,
      step,
      serviceType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanError
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.step, other.step) && MessagesPigeonUtils.deepEquals(this.serviceType, other.serviceType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.step)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.serviceType)
    return result
  }
}

/**
 * The "data persisted" payload — the full report submitted to the backend.
 * Android `DebugCallback` delivers a ~50-field `ReportParamDto`; rather than
 * re-model all 8 nested list types as Pigeon classes, we pass the SDK's
 * existing `ReportParamDto.toJson()` (Gson) string. iOS has no equivalent
 * debug callback, so this event does not fire on iOS.
 * TODO(decide): keep this event in v1, or defer richer typing to a later task.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ScanReport (
  /** Android `ReportParamDto.toJson()`. Empty/unused on iOS. */
  val reportJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanReport {
      val reportJson = pigeonVar_list[0] as String
      return ScanReport(reportJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reportJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ScanReport
    return MessagesPigeonUtils.deepEquals(this.reportJson, other.reportJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reportJson)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ScanEnvironment.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ScanStep.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ScanResultStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ScanErrorKind.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanConfig.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanProgress.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanError.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanReport.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ScanEnvironment -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ScanStep -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ScanResultStatus -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is ScanErrorKind -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is ScanConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ScanProgress -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ScanResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ScanError -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ScanReport -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ScanHostApi {
  /**
   * Android: builds `NetworkScan` via the step-builder, wiring the 4 callbacks
   * to [ScanFlutterApi], but does NOT subscribe yet.
   * iOS: constructs `ScanMyNetManager(configuration:)` and assigns the
   * delegate bridge. (init + config are fused on iOS.)
   */
  fun configure(config: ScanConfig)
  /**
   * Android: subscribes to `NetworkScan.scan()` (RxJava Single) on
   * Schedulers.io and forwards onSuccess/onError to [ScanFlutterApi].
   * iOS: calls `ScanMyNetManager.start()`.
   *
   * Intentionally NOT @async: the long-running result is delivered through
   * [ScanFlutterApi] (onFinished / onError), not a Future. This also avoids
   * double-delivery, since the result arrives via both the Rx Single AND the
   * ResultCallback on Android.
   */
  fun startScan()
  /**
   * iOS `ScanMyNetManager.cancel()`. Android has NO cancel in this fork.
   * TODO: decide Android behavior — best-effort dispose of the Rx
   * CompositeDisposable, or throw FlutterError("UNSUPPORTED").
   */
  fun cancel()

  companion object {
    /** The codec used by ScanHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ScanHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ScanHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as ScanConfig
            val wrapped: List<Any?> = try {
              api.configure(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startScan()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancel()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ScanFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ScanFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Scan started. Android: first step (SETUP). iOS: `scanStarted()`. */
  fun onStarted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Per-step progress. Android `ProgressCallback.onProgress`; iOS
   * `scanProgress` / `nextScanStarted`.
   */
  fun onProgress(progressArg: ScanProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Scan complete + report submitted. Android `ResultCallback`/Single success;
   * iOS `scanFinished(reportUrl:)`. (complete and dataPersisted are fused on
   * iOS into this single event.)
   */
  fun onFinished(resultArg: ScanResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onFinished$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * "dataPersisted": the full submitted report payload. Android
   * `DebugCallback.onResult` (ReportParamDto JSON). Does not fire on iOS.
   */
  fun onDataPersisted(reportArg: ScanReport, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onDataPersisted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(reportArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Any error state — per-step (non-fatal) or terminal submission failure. */
  fun onError(errorArg: ScanError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Scan canceled. iOS `scanCanceled()`. Never fires on Android (no cancel). */
  fun onCanceled(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onCanceled$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
