{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbucket.creativeadvtech",
    "module": "tools",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jaxb",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.0.aar",
          "url": "tools-1.0.aar",
          "size": 225482,
          "sha512": "7d53df203474127d33c76ade763836ead72b753f04c1f247853ca64e148e84f52e25a6b392ba2762fbafc301ca4f012bd1db649081f6f2e2f80b389dcb18c1b8",
          "sha256": "7116be71c39b541eba1614291c32caf33d20630dab654ce8d0f9313d8bc2617d",
          "sha1": "1b2cd72ed81e48ce4d195835a157f3a4152caaf5",
          "md5": "9dca48adec0e05cbaef564551b80cc13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.stanfy",
          "module": "gson-xml-java",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.12"
          }
        },
        {
          "group": "fr.bmartel",
          "module": "jspeedtest",
          "version": {
            "requires": "1.32.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.synaptic-tools",
          "module": "traceroute",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.github.stealthcopter",
          "module": "AndroidNetworkTools",
          "version": {
            "requires": "0.4.5.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jaxb",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.0.aar",
          "url": "tools-1.0.aar",
          "size": 225482,
          "sha512": "7d53df203474127d33c76ade763836ead72b753f04c1f247853ca64e148e84f52e25a6b392ba2762fbafc301ca4f012bd1db649081f6f2e2f80b389dcb18c1b8",
          "sha256": "7116be71c39b541eba1614291c32caf33d20630dab654ce8d0f9313d8bc2617d",
          "sha1": "1b2cd72ed81e48ce4d195835a157f3a4152caaf5",
          "md5": "9dca48adec0e05cbaef564551b80cc13"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.0-sources.jar",
          "url": "tools-1.0-sources.jar",
          "size": 59596,
          "sha512": "a704ca03ce9506fa3b2fe7a776dfb68f83f3f83f410147701e80cd6832341e3389e4bfe558984a72a2b19113c52a66adbf2f948360125e66a19e1db4a644e107",
          "sha256": "4a3e4ef6ba2ddf77c2da21ae9b090d99c0f7b53736e11ac2f8dbf6601451cfee",
          "sha1": "d1afd2bbe927516241b5df3750dd05885bb40054",
          "md5": "b816fd8bb665ec63a983431dc6779e08"
        }
      ]
    }
  ]
}
