// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// iOS `ScanMyNetConfiguration.Environment`. Android has no environment enum —
/// it takes an explicit [ScanConfig.baseUrl] string instead.
/// TODO(confirm): how iOS `environment` maps to an Android baseUrl, and whether
/// the host passes baseUrl OR environment. Native code maps explicitly; do NOT
/// rely on index parity.
enum ScanEnvironment {
  staging,
  production,
  dev,
}

/// Android `NetworkScanStep` — 13 values in source declaration order.
/// iOS has no equivalent enum (it emits a free-text stage label string), so on
/// iOS [ScanProgress.currentStep]/[nextStep] are null and [label] is set.
enum ScanStep {
  setup,
  routerUpnp,
  connectivityTest,
  speedTest,
  publicIpFetch,
  gpsLocationFetch,
  traceroute,
  wifiCongestionTest,
  wifiDiscovery,
  connectionQualityTest,
  lanDiscovery,
  additionalData,
  resultSubmission,
}

/// Android `NetworkScanResultStatus`. (Source declares
/// ERROR_SUBMISSION_FAILED, SUCCESS — we keep our own order and map explicitly
/// in native code, never by index.)
enum ScanResultStatus {
  success,
  submissionFailed,
}

/// Normalized error category across both platforms.
enum ScanErrorKind {
  /// Non-fatal, per-step failure. Android `NetworkScanError`;
  /// iOS `scanServiceFailed(type:error:)`. The scan continues.
  perStep,
  /// Terminal submission failure. Android `scan()` Single.onError;
  /// iOS `scanFailed`.
  submission,
  /// iOS `scanCanceled()`. Android has no cancel in this fork.
  canceled,
}

/// Flat configuration collapsing the Android 6-step builder and the iOS
/// `ScanMyNetConfiguration` into one message. The Android `Context` is supplied
/// by the plugin (applicationContext), so it is NOT a field here.
class ScanConfig {
  ScanConfig({
    required this.apiKey,
    this.userKey,
    this.appName,
    this.baseUrl,
    this.requestKey,
    this.environment,
  });

  /// MANDATORY on both. Android `ApiKey.apiKey`; iOS `configuration.apiKey`.
  String apiKey;

  /// Android `UserKey.userKey` (sent as ReportParamDto.key). iOS: not used.
  /// TODO(confirm): is iOS `requestKey` the same concept as Android `userKey`?
  String? userKey;

  /// Android `AppName.appName` (ReportParamDto.app). iOS: not used.
  String? appName;

  /// Android `BaseUrl.baseUrl` (Retrofit base). iOS selects backend via
  /// [environment] instead.
  String? baseUrl;

  /// iOS `ScanMyNetConfiguration.requestKey`. Android: not used.
  String? requestKey;

  /// iOS only. If null on iOS, native defaults to [ScanEnvironment.production].
  /// TODO(confirm) default environment.
  ScanEnvironment? environment;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      userKey,
      appName,
      baseUrl,
      requestKey,
      environment,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScanConfig decode(Object result) {
    result as List<Object?>;
    return ScanConfig(
      apiKey: result[0]! as String,
      userKey: result[1] as String?,
      appName: result[2] as String?,
      baseUrl: result[3] as String?,
      requestKey: result[4] as String?,
      environment: result[5] as ScanEnvironment?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) && _deepEquals(userKey, other.userKey) && _deepEquals(appName, other.appName) && _deepEquals(baseUrl, other.baseUrl) && _deepEquals(requestKey, other.requestKey) && _deepEquals(environment, other.environment);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Progress payload — superset of both platforms.
/// Android fills step/nextStep/percent/durationMs; iOS fills percent + label.
class ScanProgress {
  ScanProgress({
    required this.percent,
    this.currentStep,
    this.nextStep,
    this.label,
    this.durationMs,
  });

  /// 0..100. Native normalizes to this range.
  /// TODO(verify): Android `NetworkScanProgress.percent` is a Float documented
  /// as "percent of tests completed" — confirm 0..1 vs 0..100 and normalize in
  /// the Kotlin bridge to match iOS `scanProgress` (0..100).
  double percent;

  /// Android `NetworkScanProgress.currentStep`. Null on iOS.
  ScanStep? currentStep;

  /// Android `NetworkScanProgress.nextStep`. Null on iOS.
  ScanStep? nextStep;

  /// iOS stage label (`nextScanStarted(value)` / `serviceTriggered(log)`).
  /// Null on Android.
  String? label;

  /// Android `NetworkScanProgress.duration` (ms). Null on iOS.
  int? durationMs;

  List<Object?> _toList() {
    return <Object?>[
      percent,
      currentStep,
      nextStep,
      label,
      durationMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScanProgress decode(Object result) {
    result as List<Object?>;
    return ScanProgress(
      percent: result[0]! as double,
      currentStep: result[1] as ScanStep?,
      nextStep: result[2] as ScanStep?,
      label: result[3] as String?,
      durationMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(percent, other.percent) && _deepEquals(currentStep, other.currentStep) && _deepEquals(nextStep, other.nextStep) && _deepEquals(label, other.label) && _deepEquals(durationMs, other.durationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Terminal success. Android `ReportResponseDto.data`; iOS
/// `scanFinished(reportUrl:)`.
class ScanResult {
  ScanResult({
    required this.reportUrl,
    this.status,
    this.totalDurationMs,
  });

  /// The online report URL (Android value may carry a `verification_token`
  /// query param — leave parsing to Dart).
  String reportUrl;

  /// Android `NetworkScanResult.status`. iOS only emits on success -> SUCCESS.
  ScanResultStatus? status;

  /// Android `NetworkScanResult.duration` (total ms). Null on iOS.
  int? totalDurationMs;

  List<Object?> _toList() {
    return <Object?>[
      reportUrl,
      status,
      totalDurationMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScanResult decode(Object result) {
    result as List<Object?>;
    return ScanResult(
      reportUrl: result[0]! as String,
      status: result[1] as ScanResultStatus?,
      totalDurationMs: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(reportUrl, other.reportUrl) && _deepEquals(status, other.status) && _deepEquals(totalDurationMs, other.totalDurationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Error payload. `Throwable`/`Error`/`HTTPURLResponse` are not channel-
/// encodable, so everything is flattened to primitives here.
class ScanError {
  ScanError({
    required this.kind,
    required this.message,
    this.step,
    this.serviceType,
  });

  ScanErrorKind kind;

  /// `Throwable.message` / `Error.localizedDescription` / raw response body.
  String message;

  /// Android `NetworkScanError.test` (per-step). Null on iOS.
  ScanStep? step;

  /// iOS `scanServiceFailed` type (`ServiceType.rawValue`). Null on Android.
  String? serviceType;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      message,
      step,
      serviceType,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScanError decode(Object result) {
    result as List<Object?>;
    return ScanError(
      kind: result[0]! as ScanErrorKind,
      message: result[1]! as String,
      step: result[2] as ScanStep?,
      serviceType: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(message, other.message) && _deepEquals(step, other.step) && _deepEquals(serviceType, other.serviceType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// The "data persisted" payload — the full report submitted to the backend.
/// Android `DebugCallback` delivers a ~50-field `ReportParamDto`; rather than
/// re-model all 8 nested list types as Pigeon classes, we pass the SDK's
/// existing `ReportParamDto.toJson()` (Gson) string. iOS has no equivalent
/// debug callback, so this event does not fire on iOS.
/// TODO(decide): keep this event in v1, or defer richer typing to a later task.
class ScanReport {
  ScanReport({
    required this.reportJson,
  });

  /// Android `ReportParamDto.toJson()`. Empty/unused on iOS.
  String reportJson;

  List<Object?> _toList() {
    return <Object?>[
      reportJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static ScanReport decode(Object result) {
    result as List<Object?>;
    return ScanReport(
      reportJson: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanReport || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(reportJson, other.reportJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ScanEnvironment) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ScanStep) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ScanResultStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is ScanErrorKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is ScanConfig) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ScanProgress) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ScanResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is ScanError) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ScanReport) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ScanEnvironment.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ScanStep.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : ScanResultStatus.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ScanErrorKind.values[value];
      case 133:
        return ScanConfig.decode(readValue(buffer)!);
      case 134:
        return ScanProgress.decode(readValue(buffer)!);
      case 135:
        return ScanResult.decode(readValue(buffer)!);
      case 136:
        return ScanError.decode(readValue(buffer)!);
      case 137:
        return ScanReport.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ScanHostApi {
  /// Constructor for [ScanHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ScanHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Android: builds `NetworkScan` via the step-builder, wiring the 4 callbacks
  /// to [ScanFlutterApi], but does NOT subscribe yet.
  /// iOS: constructs `ScanMyNetManager(configuration:)` and assigns the
  /// delegate bridge. (init + config are fused on iOS.)
  Future<void> configure(ScanConfig config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Android: subscribes to `NetworkScan.scan()` (RxJava Single) on
  /// Schedulers.io and forwards onSuccess/onError to [ScanFlutterApi].
  /// iOS: calls `ScanMyNetManager.start()`.
  ///
  /// Intentionally NOT @async: the long-running result is delivered through
  /// [ScanFlutterApi] (onFinished / onError), not a Future. This also avoids
  /// double-delivery, since the result arrives via both the Rx Single AND the
  /// ResultCallback on Android.
  Future<void> startScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.startScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// iOS `ScanMyNetManager.cancel()`. Android has NO cancel in this fork.
  /// TODO: decide Android behavior — best-effort dispose of the Rx
  /// CompositeDisposable, or throw FlutterError("UNSUPPORTED").
  Future<void> cancel() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class ScanFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Scan started. Android: first step (SETUP). iOS: `scanStarted()`.
  void onStarted();

  /// Per-step progress. Android `ProgressCallback.onProgress`; iOS
  /// `scanProgress` / `nextScanStarted`.
  void onProgress(ScanProgress progress);

  /// Scan complete + report submitted. Android `ResultCallback`/Single success;
  /// iOS `scanFinished(reportUrl:)`. (complete and dataPersisted are fused on
  /// iOS into this single event.)
  void onFinished(ScanResult result);

  /// "dataPersisted": the full submitted report payload. Android
  /// `DebugCallback.onResult` (ReportParamDto JSON). Does not fire on iOS.
  void onDataPersisted(ScanReport report);

  /// Any error state — per-step (non-fatal) or terminal submission failure.
  void onError(ScanError error);

  /// Scan canceled. iOS `scanCanceled()`. Never fires on Android (no cancel).
  void onCanceled();

  static void setUp(ScanFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ScanProgress arg_progress = args[0]! as ScanProgress;
          try {
            api.onProgress(arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onFinished$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ScanResult arg_result = args[0]! as ScanResult;
          try {
            api.onFinished(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onDataPersisted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ScanReport arg_report = args[0]! as ScanReport;
          try {
            api.onDataPersisted(arg_report);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ScanError arg_error = args[0]! as ScanError;
          try {
            api.onError(arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onCanceled$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onCanceled();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
