{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbucket.creativeadvtech",
    "module": "tools",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jaxb",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.1.aar",
          "url": "tools-1.1.aar",
          "size": 286098,
          "sha512": "9bff7f60b2ec984689c129afac57c654af03dd43202b70781cdc6de26700116ca22695203ab19f0d0455184218eb544e294231f8dbedcbae06e609d72101c486",
          "sha256": "3760454008437fb7255fc995885eef87c2b9c79f70c04fa74386f7a69136c7a8",
          "sha1": "85022cf7b1a8f1c19f2713c7979dc4324780d0ae",
          "md5": "a0dc0470520122c3a93bfceb15d69241"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.stanfy",
          "module": "gson-xml-java",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.12"
          }
        },
        {
          "group": "fr.bmartel",
          "module": "jspeedtest",
          "version": {
            "requires": "1.32.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-buildtools",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.synaptic-tools",
          "module": "traceroute",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.github.stealthcopter",
          "module": "AndroidNetworkTools",
          "version": {
            "requires": "0.4.5.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-jaxb",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.1.aar",
          "url": "tools-1.1.aar",
          "size": 286098,
          "sha512": "9bff7f60b2ec984689c129afac57c654af03dd43202b70781cdc6de26700116ca22695203ab19f0d0455184218eb544e294231f8dbedcbae06e609d72101c486",
          "sha256": "3760454008437fb7255fc995885eef87c2b9c79f70c04fa74386f7a69136c7a8",
          "sha1": "85022cf7b1a8f1c19f2713c7979dc4324780d0ae",
          "md5": "a0dc0470520122c3a93bfceb15d69241"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.1-sources.jar",
          "url": "tools-1.1-sources.jar",
          "size": 70359,
          "sha512": "dcaa615887c21b76b3de01dd772492658f03f8fc80b06b7fbe456729b0ce7e08bbcc3813c4cac4078c4eb68e8c94cc9f3f0770699a00060f5731085b99599740",
          "sha256": "d88e5026354208b530175966385ef83e040c52d80623f97cb02a269158944c3e",
          "sha1": "9d46e611e267ec9e40fe7dee72777a4459ea4ccb",
          "md5": "9b6ac5410e9743250afc228bf53bf701"
        }
      ]
    }
  ]
}
