// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// iOS `ScanMyNetConfiguration.Environment`. Android has no environment enum —
/// it takes an explicit [ScanConfig.baseUrl] string instead.
/// TODO(confirm): how iOS `environment` maps to an Android baseUrl, and whether
/// the host passes baseUrl OR environment. Native code maps explicitly; do NOT
/// rely on index parity.
enum ScanEnvironment: Int {
  case staging = 0
  case production = 1
  case dev = 2
}

/// Android `NetworkScanStep` — 13 values in source declaration order.
/// iOS has no equivalent enum (it emits a free-text stage label string), so on
/// iOS [ScanProgress.currentStep]/[nextStep] are null and [label] is set.
enum ScanStep: Int {
  case setup = 0
  case routerUpnp = 1
  case connectivityTest = 2
  case speedTest = 3
  case publicIpFetch = 4
  case gpsLocationFetch = 5
  case traceroute = 6
  case wifiCongestionTest = 7
  case wifiDiscovery = 8
  case connectionQualityTest = 9
  case lanDiscovery = 10
  case additionalData = 11
  case resultSubmission = 12
}

/// Android `NetworkScanResultStatus`. (Source declares
/// ERROR_SUBMISSION_FAILED, SUCCESS — we keep our own order and map explicitly
/// in native code, never by index.)
enum ScanResultStatus: Int {
  case success = 0
  case submissionFailed = 1
}

/// Normalized error category across both platforms.
enum ScanErrorKind: Int {
  /// Non-fatal, per-step failure. Android `NetworkScanError`;
  /// iOS `scanServiceFailed(type:error:)`. The scan continues.
  case perStep = 0
  /// Terminal submission failure. Android `scan()` Single.onError;
  /// iOS `scanFailed`.
  case submission = 1
  /// iOS `scanCanceled()`. Android has no cancel in this fork.
  case canceled = 2
}

/// Flat configuration collapsing the Android 6-step builder and the iOS
/// `ScanMyNetConfiguration` into one message. The Android `Context` is supplied
/// by the plugin (applicationContext), so it is NOT a field here.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScanConfig: Hashable {
  /// MANDATORY on both. Android `ApiKey.apiKey`; iOS `configuration.apiKey`.
  var apiKey: String
  /// Android `UserKey.userKey` (sent as ReportParamDto.key). iOS: not used.
  /// TODO(confirm): is iOS `requestKey` the same concept as Android `userKey`?
  var userKey: String? = nil
  /// Android `AppName.appName` (ReportParamDto.app). iOS: not used.
  var appName: String? = nil
  /// Android `BaseUrl.baseUrl` (Retrofit base). iOS selects backend via
  /// [environment] instead.
  var baseUrl: String? = nil
  /// iOS `ScanMyNetConfiguration.requestKey`. Android: not used.
  var requestKey: String? = nil
  /// iOS only. If null on iOS, native defaults to [ScanEnvironment.production].
  /// TODO(confirm) default environment.
  var environment: ScanEnvironment? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanConfig? {
    let apiKey = pigeonVar_list[0] as! String
    let userKey: String? = nilOrValue(pigeonVar_list[1])
    let appName: String? = nilOrValue(pigeonVar_list[2])
    let baseUrl: String? = nilOrValue(pigeonVar_list[3])
    let requestKey: String? = nilOrValue(pigeonVar_list[4])
    let environment: ScanEnvironment? = nilOrValue(pigeonVar_list[5])

    return ScanConfig(
      apiKey: apiKey,
      userKey: userKey,
      appName: appName,
      baseUrl: baseUrl,
      requestKey: requestKey,
      environment: environment
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      userKey,
      appName,
      baseUrl,
      requestKey,
      environment,
    ]
  }
  static func == (lhs: ScanConfig, rhs: ScanConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.apiKey, rhs.apiKey) && deepEqualsMessages(lhs.userKey, rhs.userKey) && deepEqualsMessages(lhs.appName, rhs.appName) && deepEqualsMessages(lhs.baseUrl, rhs.baseUrl) && deepEqualsMessages(lhs.requestKey, rhs.requestKey) && deepEqualsMessages(lhs.environment, rhs.environment)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanConfig")
    deepHashMessages(value: apiKey, hasher: &hasher)
    deepHashMessages(value: userKey, hasher: &hasher)
    deepHashMessages(value: appName, hasher: &hasher)
    deepHashMessages(value: baseUrl, hasher: &hasher)
    deepHashMessages(value: requestKey, hasher: &hasher)
    deepHashMessages(value: environment, hasher: &hasher)
  }
}

/// Progress payload — superset of both platforms.
/// Android fills step/nextStep/percent/durationMs; iOS fills percent + label.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScanProgress: Hashable {
  /// 0..100. Native normalizes to this range.
  /// TODO(verify): Android `NetworkScanProgress.percent` is a Float documented
  /// as "percent of tests completed" — confirm 0..1 vs 0..100 and normalize in
  /// the Kotlin bridge to match iOS `scanProgress` (0..100).
  var percent: Double
  /// Android `NetworkScanProgress.currentStep`. Null on iOS.
  var currentStep: ScanStep? = nil
  /// Android `NetworkScanProgress.nextStep`. Null on iOS.
  var nextStep: ScanStep? = nil
  /// iOS stage label (`nextScanStarted(value)` / `serviceTriggered(log)`).
  /// Null on Android.
  var label: String? = nil
  /// Android `NetworkScanProgress.duration` (ms). Null on iOS.
  var durationMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanProgress? {
    let percent = pigeonVar_list[0] as! Double
    let currentStep: ScanStep? = nilOrValue(pigeonVar_list[1])
    let nextStep: ScanStep? = nilOrValue(pigeonVar_list[2])
    let label: String? = nilOrValue(pigeonVar_list[3])
    let durationMs: Int64? = nilOrValue(pigeonVar_list[4])

    return ScanProgress(
      percent: percent,
      currentStep: currentStep,
      nextStep: nextStep,
      label: label,
      durationMs: durationMs
    )
  }
  func toList() -> [Any?] {
    return [
      percent,
      currentStep,
      nextStep,
      label,
      durationMs,
    ]
  }
  static func == (lhs: ScanProgress, rhs: ScanProgress) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.percent, rhs.percent) && deepEqualsMessages(lhs.currentStep, rhs.currentStep) && deepEqualsMessages(lhs.nextStep, rhs.nextStep) && deepEqualsMessages(lhs.label, rhs.label) && deepEqualsMessages(lhs.durationMs, rhs.durationMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanProgress")
    deepHashMessages(value: percent, hasher: &hasher)
    deepHashMessages(value: currentStep, hasher: &hasher)
    deepHashMessages(value: nextStep, hasher: &hasher)
    deepHashMessages(value: label, hasher: &hasher)
    deepHashMessages(value: durationMs, hasher: &hasher)
  }
}

/// Terminal success. Android `ReportResponseDto.data`; iOS
/// `scanFinished(reportUrl:)`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScanResult: Hashable {
  /// The online report URL (Android value may carry a `verification_token`
  /// query param — leave parsing to Dart).
  var reportUrl: String
  /// Android `NetworkScanResult.status`. iOS only emits on success -> SUCCESS.
  var status: ScanResultStatus? = nil
  /// Android `NetworkScanResult.duration` (total ms). Null on iOS.
  var totalDurationMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanResult? {
    let reportUrl = pigeonVar_list[0] as! String
    let status: ScanResultStatus? = nilOrValue(pigeonVar_list[1])
    let totalDurationMs: Int64? = nilOrValue(pigeonVar_list[2])

    return ScanResult(
      reportUrl: reportUrl,
      status: status,
      totalDurationMs: totalDurationMs
    )
  }
  func toList() -> [Any?] {
    return [
      reportUrl,
      status,
      totalDurationMs,
    ]
  }
  static func == (lhs: ScanResult, rhs: ScanResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.reportUrl, rhs.reportUrl) && deepEqualsMessages(lhs.status, rhs.status) && deepEqualsMessages(lhs.totalDurationMs, rhs.totalDurationMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanResult")
    deepHashMessages(value: reportUrl, hasher: &hasher)
    deepHashMessages(value: status, hasher: &hasher)
    deepHashMessages(value: totalDurationMs, hasher: &hasher)
  }
}

/// Error payload. `Throwable`/`Error`/`HTTPURLResponse` are not channel-
/// encodable, so everything is flattened to primitives here.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScanError: Hashable {
  var kind: ScanErrorKind
  /// `Throwable.message` / `Error.localizedDescription` / raw response body.
  var message: String
  /// Android `NetworkScanError.test` (per-step). Null on iOS.
  var step: ScanStep? = nil
  /// iOS `scanServiceFailed` type (`ServiceType.rawValue`). Null on Android.
  var serviceType: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanError? {
    let kind = pigeonVar_list[0] as! ScanErrorKind
    let message = pigeonVar_list[1] as! String
    let step: ScanStep? = nilOrValue(pigeonVar_list[2])
    let serviceType: String? = nilOrValue(pigeonVar_list[3])

    return ScanError(
      kind: kind,
      message: message,
      step: step,
      serviceType: serviceType
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      message,
      step,
      serviceType,
    ]
  }
  static func == (lhs: ScanError, rhs: ScanError) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.kind, rhs.kind) && deepEqualsMessages(lhs.message, rhs.message) && deepEqualsMessages(lhs.step, rhs.step) && deepEqualsMessages(lhs.serviceType, rhs.serviceType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanError")
    deepHashMessages(value: kind, hasher: &hasher)
    deepHashMessages(value: message, hasher: &hasher)
    deepHashMessages(value: step, hasher: &hasher)
    deepHashMessages(value: serviceType, hasher: &hasher)
  }
}

/// The "data persisted" payload — the full report submitted to the backend.
/// Android `DebugCallback` delivers a ~50-field `ReportParamDto`; rather than
/// re-model all 8 nested list types as Pigeon classes, we pass the SDK's
/// existing `ReportParamDto.toJson()` (Gson) string. iOS has no equivalent
/// debug callback, so this event does not fire on iOS.
/// TODO(decide): keep this event in v1, or defer richer typing to a later task.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ScanReport: Hashable {
  /// Android `ReportParamDto.toJson()`. Empty/unused on iOS.
  var reportJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ScanReport? {
    let reportJson = pigeonVar_list[0] as! String

    return ScanReport(
      reportJson: reportJson
    )
  }
  func toList() -> [Any?] {
    return [
      reportJson
    ]
  }
  static func == (lhs: ScanReport, rhs: ScanReport) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.reportJson, rhs.reportJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ScanReport")
    deepHashMessages(value: reportJson, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ScanEnvironment(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ScanStep(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ScanResultStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ScanErrorKind(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return ScanConfig.fromList(self.readValue() as! [Any?])
    case 134:
      return ScanProgress.fromList(self.readValue() as! [Any?])
    case 135:
      return ScanResult.fromList(self.readValue() as! [Any?])
    case 136:
      return ScanError.fromList(self.readValue() as! [Any?])
    case 137:
      return ScanReport.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ScanEnvironment {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ScanStep {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ScanResultStatus {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ScanErrorKind {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? ScanConfig {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ScanProgress {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ScanResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ScanError {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? ScanReport {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ScanHostApi {
  /// Android: builds `NetworkScan` via the step-builder, wiring the 4 callbacks
  /// to [ScanFlutterApi], but does NOT subscribe yet.
  /// iOS: constructs `ScanMyNetManager(configuration:)` and assigns the
  /// delegate bridge. (init + config are fused on iOS.)
  func configure(config: ScanConfig) throws
  /// Android: subscribes to `NetworkScan.scan()` (RxJava Single) on
  /// Schedulers.io and forwards onSuccess/onError to [ScanFlutterApi].
  /// iOS: calls `ScanMyNetManager.start()`.
  ///
  /// Intentionally NOT @async: the long-running result is delivered through
  /// [ScanFlutterApi] (onFinished / onError), not a Future. This also avoids
  /// double-delivery, since the result arrives via both the Rx Single AND the
  /// ResultCallback on Android.
  func startScan() throws
  /// iOS `ScanMyNetManager.cancel()`. Android has NO cancel in this fork.
  /// TODO: decide Android behavior — best-effort dispose of the Rx
  /// CompositeDisposable, or throw FlutterError("UNSUPPORTED").
  func cancel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ScanHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ScanHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ScanHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Android: builds `NetworkScan` via the step-builder, wiring the 4 callbacks
    /// to [ScanFlutterApi], but does NOT subscribe yet.
    /// iOS: constructs `ScanMyNetManager(configuration:)` and assigns the
    /// delegate bridge. (init + config are fused on iOS.)
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ScanConfig
        do {
          try api.configure(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// Android: subscribes to `NetworkScan.scan()` (RxJava Single) on
    /// Schedulers.io and forwards onSuccess/onError to [ScanFlutterApi].
    /// iOS: calls `ScanMyNetManager.start()`.
    ///
    /// Intentionally NOT @async: the long-running result is delivered through
    /// [ScanFlutterApi] (onFinished / onError), not a Future. This also avoids
    /// double-delivery, since the result arrives via both the Rx Single AND the
    /// ResultCallback on Android.
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.startScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { _, reply in
        do {
          try api.startScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    /// iOS `ScanMyNetManager.cancel()`. Android has NO cancel in this fork.
    /// TODO: decide Android behavior — best-effort dispose of the Rx
    /// CompositeDisposable, or throw FlutterError("UNSUPPORTED").
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.scanmynet_sdk.ScanHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { _, reply in
        do {
          try api.cancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ScanFlutterApiProtocol {
  /// Scan started. Android: first step (SETUP). iOS: `scanStarted()`.
  func onStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Per-step progress. Android `ProgressCallback.onProgress`; iOS
  /// `scanProgress` / `nextScanStarted`.
  func onProgress(progress progressArg: ScanProgress, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Scan complete + report submitted. Android `ResultCallback`/Single success;
  /// iOS `scanFinished(reportUrl:)`. (complete and dataPersisted are fused on
  /// iOS into this single event.)
  func onFinished(result resultArg: ScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// "dataPersisted": the full submitted report payload. Android
  /// `DebugCallback.onResult` (ReportParamDto JSON). Does not fire on iOS.
  func onDataPersisted(report reportArg: ScanReport, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Any error state — per-step (non-fatal) or terminal submission failure.
  func onError(error errorArg: ScanError, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Scan canceled. iOS `scanCanceled()`. Never fires on Android (no cancel).
  func onCanceled(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ScanFlutterApi: ScanFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Scan started. Android: first step (SETUP). iOS: `scanStarted()`.
  func onStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Per-step progress. Android `ProgressCallback.onProgress`; iOS
  /// `scanProgress` / `nextScanStarted`.
  func onProgress(progress progressArg: ScanProgress, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Scan complete + report submitted. Android `ResultCallback`/Single success;
  /// iOS `scanFinished(reportUrl:)`. (complete and dataPersisted are fused on
  /// iOS into this single event.)
  func onFinished(result resultArg: ScanResult, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onFinished\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// "dataPersisted": the full submitted report payload. Android
  /// `DebugCallback.onResult` (ReportParamDto JSON). Does not fire on iOS.
  func onDataPersisted(report reportArg: ScanReport, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onDataPersisted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([reportArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Any error state — per-step (non-fatal) or terminal submission failure.
  func onError(error errorArg: ScanError, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Scan canceled. iOS `scanCanceled()`. Never fires on Android (no cancel).
  func onCanceled(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.scanmynet_sdk.ScanFlutterApi.onCanceled\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
